name: ab_shared
description: "A new Flutter package project."
version: 0.2.0
homepage: https://github.com/atomic-blend/ab_shared

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_age:
    git: # ignore: invalid_dependency
      url: https://github.com/atomic-blend/flutter_age.git
      ref: v0.0.5
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  pointycastle: ^3.9.1
  bip39: ^1.0.6
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.4.0
  device_info_plus: ^11.5.0
  flutter_timezone: ^4.1.1
  purchases_flutter: ^9.2.0
  dio: ^5.9.0
  sentry_flutter: ^9.6.0
  pretty_dio_logger: ^1.4.0
  injectable: ^2.5.1
  hydrated_bloc: ^10.1.1
  flex_color_scheme: ^8.2.0
  sizer: ^3.0.5
  flutter_bloc: ^9.1.1
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.2
  icons_plus: ^5.0.0
  lottie: ^3.3.1
  toastification: ^3.0.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  random_avatar: ^0.0.8
  url_launcher: ^6.3.2
  jiffy: ^6.4.3
  unique_name_generator: ^1.0.0
  animated_toggle_switch: ^0.8.5
  async: ^2.13.0
  qr_flutter: ^4.1.0
  flex_color_picker: ^3.7.1
  timezone: ^0.10.1
  syncfusion_flutter_datepicker: ^30.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  slang_build_runner: ^4.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
